### ISSUE TITLE
Field from the document for the data_stream.namespace 

### ISSUE THREAD

**Issue by b2ronn** [elastic/fleet-server#1227]
if I specify "${kubernetes.namespace}" in the namespace field, in the integration through kibana, then I get the error 
{"log.level":"error","@timestamp":"2022-03-15T14:43:26.432Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":181},"message":"failed to dispatch actions, error: could not convert the configuration from the policy: missing field accessing 'output_permissions'","ecs.version":"1.6.0"}
how to specify variable for namespace?

![image](https://user-images.githubusercontent.com/20790707/158403992-19d9301c-6ec2-4105-86e3-69305239ea1b.png)
ps:
OpenShift version 4.9.10
Elasticsearch (ECK) Operator 2.1.0 provided by Elastic
elastic/kibana/fleet/agent - 8.1

**Comment by b2ronn** [comment]
if i specify namespace as -  $${kubernetes.namespace}

```
inputs:
- apm-server:
  data_stream:
    namespace: $${kubernetes.namespace}
...
output_permissions:
  default:
    _elastic_agent_checks:
      cluster:
      - monitor
    apm-1:
      cluster:
      - cluster:monitor/main
      indices:
      - names:
        - logs-apm.app-${kubernetes.namespace}
        privileges:
        - auto_configure
        - create_doc
      - names:
        - metrics-apm.app.*-${kubernetes.namespace}
        privileges:
        - auto_configure
        - create_doc
```
but the data doesn't come in that way.
