### ISSUE TITLE
Cache configuration keys should be under the input

### ISSUE THREAD

**Issue by blakerouse** [elastic/fleet-server#155]
At the moment the newly added `cache` key is at the top-level of the configuration. It should have been added nested under the input:

```
inputs:
  - type: fleet-server
    cache:
       ...
```

Without it in this structure these values will never be able to be adjusted when running under Agent, which is the only officially supported way of running Fleet Server.
