### ISSUE TITLE
ECK Fleet TLS Disabled NOT Working

### ISSUE THREAD

**Issue by aung-mm** [elastic/fleet-server#1666]
I would like to disable TLS in the fleet server that I deployed with eck. According to documentation, I should be able to disable with "http" configuration. But it is not working at all.
Please see the following configuration. Thanks.

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: test-fleet-server
  namespace: test
spec:
  http:
    service:
      spec:
        type: NodePort  
    tls:
      selfSignedCertificate:
        disabled: true

  version: 8.2.2
  kibanaRef:
    name: test
  elasticsearchRefs:
  - name: test
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: test-elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-elastic-agent
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-elastic-agent
subjects:
- kind: ServiceAccount
  name: test-elastic-agent
  namespace: test
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io
```
