### ISSUE TITLE
Fleet Server configuration does not contain all the hosts available in the Elasticsearch cluster

### ISSUE THREAD

**Issue by mrodm** [elastic/fleet-server#2635]
- Version: 8.7.1 (and probably newer versions)
- Operating System: Linux
- Discuss Forum URL: N/A

Following the instructions to enroll a new Fleet Server, if the host used in the install command is down or stopped, fleet-server becomes unhealhty (and all the agents connected to it).

## Steps to Reproduce:

- Setup a Elastic stack cluster with 3 Elasticsearch hosts and 1 Kibana.
    - Ensure that the 3 ES hosts are accessible to port 9200
        - In this example, these ES hosts are accessible through:
            - https://10.13.233.1:9200
            - https://10.13.233.1:9201
            - https://10.13.233.1:9202
    - Ensure that Kibana has configured the 3 ES hosts in its configuration.
- Add in the Fleet Settings, all three hosts available in the Output
  ![fleet output configuration](https://github.com/elastic/elastic-agent/assets/5330827/2a359441-de6f-4ffa-bbd8-678eaa735686)

- Create a new VM. In this VM, enroll a new fleet-server using the command suggested by the UI in another VM.
    - NOTE: there is just one ES host set in the `--fleet-server-es` parameter
    - Added some parameters to avoid issues with SSL/TLS
      ```bash
      sudo ./elastic-agent install \
        --fleet-server-es=https://10.13.233.1:9200 \
        --fleet-server-es-ca=/home/ubuntu/ca/ca.crt \
        --fleet-server-es-insecure \
        --insecure \
        --fleet-server-service-token=<token> \
        --fleet-server-policy=fleet-server-policy
      ```
- Create another VM. In this VM, enroll a new agent following the instructions too.
    - Adding `--insecure` to avoid issues with SSL/TLS
      ```
      sudo ./elastic-agent install \
        --url=https://fleetserver:8220 \
        --enrollment-token=<token> \
        --insecure
      ```
- Confirm that there are logs in Elasticsearch
  ![logs from fleet server and agent](https://github.com/elastic/fleet-server/assets/5330827/5fade219-bd41-4b6a-b5f0-7353a1c5fa05)

At this point, this new fleet-server should be shown in the Fleet view along with the agents:
![fleet healthy](https://github.com/elastic/fleet-server/assets/5330827/40c8db94-5259-4823-8026-60604cdcb3d9)

In this stage, if any ES host different to the one used in the `install` command is stopped, there are no issues with fleet-server or any agent that has been installed:
- Agents and fleet server are healthy
- Agents and Fleet server are ingesting logs

However, if the ES host (`https://10.13.233.1:9200`) used in the install command (`--fleet-server-es`) is down:
- fleet-server becomes **unhealhty** as well as the agents.
- both fleet-server and agents are still sending data (logs) to Elasticsearch

![unhealthy fleet server and agents](https://github.com/elastic/fleet-server/assets/5330827/a0611abf-b429-46cc-8448-76f7ed663346)

![logs still are sent](https://github.com/elastic/fleet-server/assets/5330827/336f5f39-41f4-4061-bc2a-7bcdc5ea7093)

Thanks to this PR https://github.com/elastic/fleet-server/pull/2632, when the fleet-server was healthy, a diagnostics bundle was generated and in the fleet-server configuration there is just one Elasticsearch host (the one used in the install command).

```yaml
fleet:
    agent:
        id: e1a89fa0-5c2a-41ed-a267-b615ebb34f92
        version: 8.7.1
        logging:
            level: info
    host:
        id: ""
        name: ""
output:
    elasticsearch:
        protocol: https
        hosts:
            - 10.13.233.1:9200
        path: ""
        headers: {}
        apikey: ""
        servicetoken: '[redacted]'
        proxyurl: ""
        proxydisable: false
        proxyheaders: {}
        tls:
            verification_mode: none
            certificate_authorities:
                - /home/ubuntu/ca/ca.crt
            renegotiation: never
        maxretries: 3
        maxconnperhost: 128
        timeout: 1m30s
        maxcontentlength: 104857600
...
```

**Comment by michel-laterman** [comment]
We have a [unit test](https://github.com/elastic/fleet-server/blob/main/internal/pkg/config/output_test.go#L86) that validates that multiple hosts should be placed in the resulting es output config.
Additionally I was able to run a quick test on a stand-alone agent to ensure that multiple outputs are used.
```yml
output:
  elasticsearch:
    hosts:
      - https://localhost:9200
      - https://192.168.4.20:9200
```
resulted in log entries indicating both hosts are used:
```
19:36:27.201 INF elasticsearch cluster info cluster.addr=["https://localhost:9200","https://192.168.4.20:9200"] cluster.maxConnsPersHost=128 cluster.name=elasticsearch cluster.uuid=SF4hcNkaQSiUPSjJxpJyyQ cluster.version=8.9.0-SNAPSHOT ecs.version=1.6.0 service.name=fleet-server
19:36:27.201 DBG init es cluster.addr=["https://localhost:9200","https://192.168.4.20:9200"] cluster.maxConnsPersHost=128 ecs.version=1.6.0 service.name=fleet-server
19:36:27.217 INF elasticsearch cluster info cluster.addr=["https://localhost:9200","https://192.168.4.20:9200"] cluster.maxConnsPersHost=128 cluster.name=elasticsearch cluster.uuid=SF4hcNkaQSiUPSjJxpJyyQ cluster.version=8.9.0-SNAPSHOT ecs.version=1.6.0 service.name=fleet-server
```

This looks like it's specific to how the agent client sends the config to the fleet server instance.
Either when [agent.reconfigure](https://github.com/elastic/fleet-server/blob/main/internal/pkg/server/agent.go#L328) is called, or when the underlying server [checks the passed config](https://github.com/elastic/fleet-server/blob/main/internal/pkg/server/fleet.go#L176). I'll investigate these
