### ISSUE TITLE
Fleet Server APM instrumentation is not working

### ISSUE THREAD

**Issue by ablnk** [elastic/fleet-server#2689]
**Precondition:**
Create a deployment of 8.9.0-SNAPSHOT in QA cloud environment.

**Impacted package:**
`fleet_server:1.3.0`

**Steps to reproduce:**

1. Change the Fleet Server configuration in the Elastic Cloud agent policy by adding the following:

```
server.instrumentation:
  enabled: true
  hosts:
  - <apm server url>
  secret_token: <>
  transaction_sample_rate: 0.05
```

Get `apm server url` and `secret_token` directly from Elastic APM integration in the Elastic Cloud agent policy.

2. Open the APM section in Kibana and check if data is available.

**Actual result:**
The APM page suggests adding a data source:

![image](https://github.com/elastic/fleet-server/assets/34958359/48b25ad2-e4be-4cb1-bd80-cfd2ea289a60)

Fleet Server is shown as unhealthy in Fleet:
![image](https://github.com/elastic/fleet-server/assets/34958359/c843f55f-7692-4ca9-8f49-503d6f729572)

**Expected result:**
Fleet Server data is available in the APM.
