### ISSUE TITLE
ECK 8.9.0 Enrollment failed

### ISSUE THREAD

**Issue by khteh** [elastic/fleet-server#2871]
```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: default
spec:
  version: 8.9.0
  kibanaRef:
    name: kyberlife
  elasticsearchRefs:
    - name: my-es
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 3
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
```
```
Error: fleet-server failed: context canceled
Error: enrollment failed: exit status 1
```
For confirmed bugs, please report:
- Version:  8.9.0
- Operating System:  Ubuntu
- Discuss Forum URL:
- Steps to Reproduce:
