### ISSUE TITLE
[Fleet] Return a 404 when a static policy do not exists yet

### ISSUE THREAD

**Issue by nchaulet** [elastic/fleet-server#3068]
## Description 

We allow to specify a list of static tokens with `static_policy_tokens` but if the policy do not exist the enroll endpoint will return a 500.

I think we should probably handle this by returning a 404 

it will mitigate the cloudbeat issue @kpollich does it make sense to you? 

## How to reproduce 

1. Create an API key in ES 
2. add that API key your fleet server config without any policy assigned to it 
```
inputs:
  - type: fleet-server
    policy.id: "${FLEET_SERVER_POLICY_ID:fleet-server-policy}"
    static_policy_tokens:
      enabled: true
      policy_tokens:
        - # policy_id is the id of the policy the token is associated with.
          policy_id: "test123"
          # token_key is the key used to authenticate the token.
          token_key: "<API_KEY>"
```
