### ISSUE TITLE
Replace secret vars for arrays

### ISSUE THREAD

**Issue by juliaElastic** [elastic/fleet-server#3083]
When implementing replacement of secret vars in agent policies [here](https://github.com/elastic/fleet-server/pull/2863), we left out a scenario when the variables can have array values.

See thread [here](https://github.com/elastic/kibana/issues/154715#issuecomment-1792869195) for more info.

Expected fix: check if vars have array values, replace secrets in them.

To reproduce:

- Add `secret: true` to the [manifest](https://github.com/elastic/integrations/blob/main/packages/ti_otx/data_stream/threat/manifest.yml) locally:

```
      - name: api_token
        type: text
        title: API Token
        multi: false
        required: true
        show_user: true
        description: The Alienvault OTX API token
        secret: true
```

- Add AlienVault OTX integration and populate the API token/key.
- Enroll an agent and check the agent policy sent to the agent.
- The secrets in `request.transforms` should be replaced.

```
    streams:
      - id: httpjson-ti_otx.threat-a520c8d4-1c8e-48c6-8525-d046ab1b8bda
        data_stream:
          dataset: ti_otx.threat
          type: logs
        config_version: '2'
        interval: 5m
        request.method: GET
        request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
        request.url: 'https://otx.alienvault.com/api/v1/indicators/export'
        request.timeout: 30s
        request.transforms:
          - set:
              target: header.Content-Type
              value: application/json
          - set:
              target: header.X-OTX-API-KEY
              value: '${SECRET_0}'
```
