### ISSUE TITLE
[Self-Managed]: Fleet Server permanently goes offline and memory consumption increases on changing logging level to debug.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#3485]
**Kibana Build details:**
```
VERSION: 8.14.0 BC1
BUILD: 73520
COMMIT: c1513cd7e5a00eab209ba02d30cafd6945d75470
```
Artifact Link: https://staging.elastic.co/8.14.0-a40d088a/summary-8.14.0.html

**Host OS:**  All

**Preconditions:**
1. 8.14.0-BC1 Kibana self-managed environment should be available.
2. Fleet Server should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Agents>Agent logs tab.
2. Update logging level to debug.
3. Observe fleet-server gets offline permanently and memory consumption increases.

**Expected Result:**
Fleet Server should remain Healthy on changing logging level to debug.

**Logs:**
[elastic-agent-diagnostics-2024-04-23T04-48-12Z-00.zip](https://github.com/elastic/fleet-server/files/15071605/elastic-agent-diagnostics-2024-04-23T04-48-12Z-00.zip)

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/228d69e6-7de4-44b3-bd4d-b7391d25eb44)

**Note:**
- Issue is consistently reproducible at our end.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
```yaml
components:
    - id: fleet-server-default
      state:
        component:
            apmconfig: null
            limits:
                gomaxprocs: 0
                source:
                    fields:
                        go_max_procs:
                            kind:
                                numbervalue: 0
        component_idx: 2
        features_idx: 2
        message: 'Healthy: communicating with pid ''6060'''
        state: 2
        units:
            input-fleet-server-default-fleet-server-fleet_server-a4eeee2f-bf68-436c-8c3f-f860be6f8299:
                message: 'Error - could not start the HTTP server for the API: failed to listen on the named pipe \\.\pipe\UwGGXFL1il700DVAc6q-T-1Z9J1UjGMU.sock: open \\.\pipe\UwGGXFL1il700DVAc6q-T-1Z9J1UjGMU.sock: Access is denied.'
                state: 4
            output-fleet-server-default:
                message: 'Error - could not start the HTTP server for the API: failed to listen on the named pipe \\.\pipe\UwGGXFL1il700DVAc6q-T-1Z9J1UjGMU.sock: open \\.\pipe\UwGGXFL1il700DVAc6q-T-1Z9J1UjGMU.sock: Access is denied.'
                state: 4
        version_info:
            build_hash: "11861004"
            meta:
                build_time: 2024-04-18 09:05:58 +0000 UTC
                commit: "11861004"
            name: fleet-server

fleet_message: |+
    fail to checkin to fleet-server: all hosts failed: 1 error occurred:
    	* requester 0/1 to host https://localhost:8221/ errored: Post "https://localhost:8221/api/fleet/agents/f9489d84-c941-40ef-84eb-e07adcf4b37c/checkin?": dial tcp 127.0.0.1:8221: connectex: No connection could be made because the target machine actively refused it.

fleet_state: 4
log_level: debug
message: 1 or more components/units in a failed state
state: 3

```
