### ISSUE TITLE
Users were able to change the fleet server service token after installation

### ISSUE THREAD

**Issue by kaanyalti** [elastic/fleet-server#4573]
A user was able to provide a new service token to the fleet server after installation by following the steps below

1. Change the existing output from `Elasticsearch` to `Elasticsearch (Remote)`
2. Generate a new service token and assign it to the output
3. Change the type back to `Elasticsearch`

This should not be possible

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: Upgraded from 8.14.3 to 8.17.2
- Operating System: 
```
runtime:
    arch: amd64
    native_arch: amd64
    os: linux
    osinfo:
        family: debian
        major: 22
        minor: 4
        patch: 5
        type: linux
        version: 22.04.5 LTS (Jammy Jellyfish)
```
- Discuss Forum URL:
- Steps to Reproduce: Outlined above
