### ISSUE TITLE
Handle new `Migrate` action and ACK type

### ISSUE THREAD

**Issue by michalpristas** [elastic/fleet-server#4785]
### DoD
- [ ] OpenAPI spec is updated to include `MIGRATE` action
- [ ] Fleet server recognizes new `MIGRATE` action (definition below) 
- [ ] Fleet server can ACK `MIGRATE` action
- [ ] Tests are up to date with new action set

### Action definition

```yml
MigrateAction:
 type: object
 properties:
   id:
     type: string
     description: Unique identifier for the action.
   type:
     type: string
     description: Type of the action.
   target_uri:
     type: string
     description: URI of Fleet Server in a target cluster
   enrollment_token:
     type: string
     description: Enrollment token used to enroll agent to a new cluster
   settings:
     description: |
      An embedded JSON object that holds user-provided settings like TLS.
      Defined in fleet-server as a `json.RawMessage`.
     type: string
     format: application/json
     x-go-type: json.RawMessage
 required:
   - id
   - type
   - policy_id
```

Supported keys for settings are (more details [here](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#_options_2)):
- ca-sha256
- certificate-authorities
- elastic-agent-cert
- elastic-agent-cert-key
- elastic-agent-cert-key-passphrase
- header
- insecure
- proxy-disabled
- proxy-header
- proxy-url
- staging
- tag
- replace-token

follow camelCase for naming properties in settings json object
