### ISSUE TITLE
Add `rollback` boolean field to ActionUpgrade

### ISSUE THREAD

**Issue by pchila** [elastic/fleet-server#4838]
Add a `rollback` boolean field (defaults to false) in upgrade action and propagate it to elastic-agent upgrade entry point.
The new upgrade action schema should look like:
```yaml
actionUpgrade:
  description: the UPGRADE action data.
  type: object
  required:
    - version
  properties:
    version:
      description: The version number that the agent should upgrade to.
      type: string
    source_uri:
      description: The source of the upgrade artifact.
      type: string
    rollback:
      description: Indicates if this version change should be performed as a rollback to a previous version.
      type: boolean
```
