### ISSUE TITLE
fleet-server username/password authentication must be removed in 8.0

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#978]
**Describe the enhancement:**
Write access to Elasticsearch using username/password must be totally removed.

**Describe a specific use case for the enhancement or feature:**

**Comment by ruflin** [comment]
It needs to be made sure also all the related code in Elastic Agent is removed too.

**Comment by michel-laterman** [comment]
username/password has been removed from the fleet-server and elastic-agent in 8.1 and backported to 8.0.
The docs pr for this is: https://github.com/elastic/observability-docs/pull/1423

**Comment by dikshachauhan-qasource** [comment]
Hi @jlind23 

We have validated this ticket on 8.0 rc1 BC1 build self managed environment and found it working fine there.

**Steps included:**
- Set up a self managed env on 8.0 rc1 bc1 build.
- Access Kibana and install Fleet server agent under Default fleet server policy.
- Wait agent to be available on Fleet and running as Healthy.
- Now access location: C:\Program Files\Elastic\Agent and open Fleet.yml file
- Scroll down to outputs section.

**Observation:** 
- No username and password key were available in Fleet.yml under output section.
- Service token value was available.
```
output:
      elasticsearch:
        protocol: https
        hosts:
        - 10.0.7.38:9200
        service_token: AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDE5MDAzNTk1NjA6SXZ4d29zSnZTY0M5a3kxbVFoalItQQ
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/148938997-06935356-85d1-4180-81bd-7794ec8d127b.png)

**Build details:**
```
BUILD 48917
COMMIT 51f4ded427abb6fd96c7d65e179fb367d450448c
Artifact link: https://staging.elastic.co/8.0.0-rc1-da1f5893/summary-8.0.0-rc1.html
```

Thanks
QAS
